.decl prestate(player : number, frame: number, state: number)
.input prestate

.decl poststate(player : number, frame: number, state: number)
.input poststate

.decl Trans(player :number, s1 : number, s2 :number, ts :number)

Trans(player, s1, s2, ts):-
  prestate(player, ts, s1),
  poststate(player, ts, s2).

.output Trans

.decl UpSmash(player : number, ts : number)

UpSmash(player, ts) :-
  Trans(player, s1, 63, ts),
  s1 != 63.

.output UpSmash
